language: android
jdk: oraclejdk8
sudo: false
android:
  components:
  - platform-tools
  - tools
  - build-tools-24.0.0
  - android-24
  - android-22
  - extra-android-m2repository
  - sys-img-armeabi-v7a-android-22
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
before_install:
- wget http://services.gradle.org/distributions/gradle-2.14-bin.zip
- unzip gradle-2.14-bin.zip
- export GRADLE_HOME=$PWD/gradle-2.14
- export PATH=$GRADLE_HOME/bin:$PATH
- gem install fir-cli
  after_deploy:
    - fir p app/build/outputs/apk/app-release.apk -T $FIR_TOKEN -c "`git cat-file tag $TRAVIS_TAG`"


script: gradle assembleRelease
deploy:
  provider: releases
  api_key:
    secure: Kjd3GltyVjkEaaToNY8L3JHzCSCfawpx1Mmd4vbbBmwVBVt3qBlDqRhEh8KYeZB1jeh935BxJetw6OAakJPrVbgOa2EjLRSfcAaxMo7AWDrrdoef4SZU8pPXCF9nJ0xoq4ysACPyabjukemsk8ydE4/b/4vjPt/z1eVBRzep00mLNqsCbWiNtp2B+xBzOu1ueHABjIjq25dKD2MFUUEJqKcaZNV8s3P0JZLZcyWnJ9MlZxCesbcDFacCfDFg6SzlD8LahuSRmeH8qnw8vLRMitrNV/o5YcSn5a6ygOJaI9gYp8X3sVVjIPCRtPuBRR7XMVEhzXVfRbPsKbU4xxp7Zvmxz17HVyCkRLq6Qulz4nQ2twcepElxnTPIVWyATz97ZCmCfsGaSUqiZBu5LHGCUPOfsU/oD7seMhJMzaEg8g2N9ySv2Mgp8ZRmr28zsB53gCHzOty3FNVh4FkszsJ1mXUfj8ZF9DpUdJt90vL/nWVy8x4BZ0i5LoMCVUGA2PtEVyVsziM62kVxFhd7tFYwvpXAzChgsxOZBQKwO2cW3Pr6VE/6j9dFqy6teI8jrsas6oc9R1TQ6YFFmVw1RU4cCJuujqsAzW3T/LLviHvCO6Pow8v9RZS0fRqzhJLAeDAtAfjfsfvzT/6S8fCKDjVtUn44kbjvMi2MIh5f2nZjSUo=
  file: app/build/outputs/apk/app-release.apk
  on:
    repo: skyJinc/SkyApp